/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OperationType } from './operation-type';

/**
 * Each possible value of `OperationType`
 */
export const OPERATION_TYPE: OperationType[] = [
  'Add',
  'Remove',
  'Replace',
  'Move',
  'Copy',
  'Test',
  'Invalid'
];