/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OperationType } from '../models/operation-type';
export interface Operation {
  from?: string | null;
  op?: string | null;
  operationType?: OperationType;
  path?: string | null;
  value?: any | null;
}
