/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TodoStatus } from '../models/todo-status';
export interface TodoDto {
  createdDate?: string;
  description?: string | null;
  dueDate?: string | null;
  id: number;
  name: string;
  status: TodoStatus;
}
