/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TodoStatus } from '../models/todo-status';
export interface TodoForUpdateDto {
  description?: string | null;
  dueDate?: string | null;
  name: string;
  status: TodoStatus;
}
