/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TodoStatus } from './todo-status';

/**
 * Each possible value of `TodoStatus`
 */
export const TODO_STATUS: TodoStatus[] = [
  'ToDo',
  'InProgress',
  'Completed',
  'Archived'
];