/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { ApiAuthenticationAuthenticatePost$Plain$Params as ApiAuthenticationAuthenticatePost$Plain$Params } from './fn/authentication/api-authentication-authenticate-post-plain';
export { apiAuthenticationAuthenticatePost$Plain as apiAuthenticationAuthenticatePost$Plain } from './fn/authentication/api-authentication-authenticate-post-plain';
export type { ApiAuthenticationAuthenticatePost$Params as ApiAuthenticationAuthenticatePost$Params } from './fn/authentication/api-authentication-authenticate-post';
export { apiAuthenticationAuthenticatePost as apiAuthenticationAuthenticatePost } from './fn/authentication/api-authentication-authenticate-post';
export type { ApiTodoGet$Params as ApiTodoGet$Params } from './fn/todo/api-todo-get';
export { apiTodoGet as apiTodoGet } from './fn/todo/api-todo-get';
export type { ApiTodoPost$Params as ApiTodoPost$Params } from './fn/todo/api-todo-post';
export { apiTodoPost as apiTodoPost } from './fn/todo/api-todo-post';
export type { GetTodo$Params as GetTodo$Params } from './fn/todo/get-todo';
export { getTodo as getTodo } from './fn/todo/get-todo';
export type { ApiTodoIdPut$Params as ApiTodoIdPut$Params } from './fn/todo/api-todo-id-put';
export { apiTodoIdPut as apiTodoIdPut } from './fn/todo/api-todo-id-put';
export type { ApiTodoIdDelete$Params as ApiTodoIdDelete$Params } from './fn/todo/api-todo-id-delete';
export { apiTodoIdDelete as apiTodoIdDelete } from './fn/todo/api-todo-id-delete';
export type { ApiTodoIdPatch$Params as ApiTodoIdPatch$Params } from './fn/todo/api-todo-id-patch';
export { apiTodoIdPatch as apiTodoIdPatch } from './fn/todo/api-todo-id-patch';
