/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoDto } from '../../models/todo-dto';
import { TodoStatus } from '../../models/todo-status';

export interface ApiTodoGet$Params {
  Name?: string;
  SearchQuery?: string;
  Statuses?: Array<TodoStatus>;
  SortBy?: string;
  SortOrder?: string;
  PageNumber?: number;
  PageSize?: number;
}

export function apiTodoGet(http: HttpClient, rootUrl: string, params?: ApiTodoGet$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TodoDto>>> {
  const rb = new RequestBuilder(rootUrl, apiTodoGet.PATH, 'get');
  if (params) {
    rb.query('Name', params.Name, {});
    rb.query('SearchQuery', params.SearchQuery, {});
    rb.query('Statuses', params.Statuses, {"style":"form","explode":false});
    rb.query('SortBy', params.SortBy, {});
    rb.query('SortOrder', params.SortOrder, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TodoDto>>;
    })
  );
}

apiTodoGet.PATH = '/api/todo';
