/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TodoDto } from '../../models/todo-dto';

export interface GetTodo$Params {
  id: number;
}

export function getTodo(http: HttpClient, rootUrl: string, params: GetTodo$Params, context?: HttpContext): Observable<StrictHttpResponse<TodoDto>> {
  const rb = new RequestBuilder(rootUrl, getTodo.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TodoDto>;
    })
  );
}

getTodo.PATH = '/api/todo/{id}';
